# -*- coding: utf-8 -*-
"""dmvlab_riadoan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ls02NwUkQ-DRBWzKuy0bycDyYAeSH6nX
"""

import pandas as pd

# Upload file in Colab
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv('Companies_dataset.csv')

df.head()

# Remove unwanted column
df = df.drop(columns=['Unnamed: 0'])

# Clean review_count (remove text and convert to number)
df['review_count'] = df['review_count'].str.replace('[(), Reviewsk+]', '', regex=True)
df['review_count'] = pd.to_numeric(df['review_count'], errors='coerce')

# Extract numeric years
df['years'] = df['years'].str.extract('(\d+)').astype(float)

# Clean employees (convert to categories or numbers)
df['employees_clean'] = df['employees'].str.extract('(\d+)')

top10 = df.sort_values(by='ratings', ascending=False).head(10)

print(top10[['name', 'ratings', 'hq']])

import plotly.express as px

fig = px.funnel(top10, x='review_count', y='name',
                title='Funnel Chart: Company Reviews')

fig.show()

import matplotlib.pyplot as plt

plt.figure()
plt.bar(top10['name'], top10['years'])
plt.xticks(rotation=45)
plt.title('Bar Chart: Company vs Years')
plt.xlabel('Company')
plt.ylabel('Years')

plt.show()

plt.figure()
plt.plot(top10['name'], top10['ratings'], marker='o')
plt.xticks(rotation=45)
plt.title('Line Chart: Company Ratings')
plt.xlabel('Company')
plt.ylabel('Ratings')

plt.show()

# Count employee categories
emp_counts = df['employees'].value_counts().head(5)

plt.figure()
plt.pie(emp_counts, labels=emp_counts.index, autopct='%1.1f%%')
plt.title('Pie Chart: Employee Distribution')

plt.show()